apiVersion: v1
kind: Service
metadata:
  name: music-api
spec:
  type: NodePort
  selector:
    app: music-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-api
spec:
  selector:
    matchLabels:
      app: music-api
  replicas: 1
  template:
    metadata:
      labels:
        app: music-api
    spec:
      containers:
      - name: music-api
        image: samlangley/music-api:latest
        imagePullPolicy: "Always"
        env:
        - name: SPOTIFY_ID
          valueFrom:
            secretKeyRef:
              name: music-api-m7bdm88fh2
              key: SPOTIFY_ID
        - name: SPOTIFY_SECRET
          valueFrom:
            secretKeyRef:
              name: music-api-m7bdm88fh2
              key: SPOTIFY_SECRET
        ports:
        - containerPort: 5000
